---
# tasks file for server

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600
      become: yes

    - name: Installation install software-properties-common
      apt: name=software-properties-common
      become: yes

    - name: "Repo PHP 7.4"
      apt_repository:
        repo="ppa:ondrej/php"

    - name: "Updating the Repo"
      apt: update_cache=yes

    - name: Installation PHP 7.4
      apt: name=php7.4 state=present update_cache=yes

    - name: Installation python3-pymysql
      apt: name=python3-pymysql state=present update_cache=yes

    - name: Install php7.4-mysql
      apt: name=php7.4-mysql state=present update_cache=yes

    - name: Install LAMP Stack
      apt:	
        pkg:
          - php7.4-mysql
          - php7.4-curl
          - php7.4-json
          - php7.4-cgi
          - php7.4-xsl
          - php7.4-cgi
          - php7.4-gd
          - php7.4-mbstring
          - php7.4-zip
          - php7.4-xmlrpc
          - php7.4-soap
          - php7.4-intl
          - libapache2-mod-php
        state: present
        update_cache: yes 

